import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
const read = (...parts) => readFileSync(resolve(repo, ...parts), 'utf8');

test('cloud transcription credentials have no build-time source', () => {
  const build = read('app', 'build.sh');
  const envExample = read('app', '.env.example');
  const secrets = read('app', 'Sources', 'MeetGPT', 'Secrets.swift');

  for (const variable of ['DEEPGRAM_API_KEY', 'ASSEMBLYAI_API_KEY']) {
    assert.ok(!build.includes(variable), `${variable} is still read or generated by build.sh`);
    assert.ok(!envExample.includes(variable), `${variable} is still advertised as a .env input`);
  }
  assert.ok(!/static let (deepgram|assemblyAI)APIKey\b/.test(secrets),
    'tracked Secrets.swift still defines a transcription credential');
});

test('distribution allowlists exact non-secret transcription settings', () => {
  const build = read('app', 'build.sh');
  const caseStart = build.indexOf('case "$1" in');
  const caseEnd = build.indexOf('\n        esac', caseStart);
  assert.ok(caseStart >= 0 && caseEnd > caseStart, 'sw distribution allowlist was not found');
  const allowlist = build.slice(caseStart, caseEnd);
  const settingsArmEnd = allowlist.indexOf(') : ;;');
  assert.ok(settingsArmEnd > 0, 'sw exact-settings arm was not found');
  const settingsArm = allowlist.slice(0, settingsArmEnd);

  assert.ok(!settingsArm.includes('TRANSCRIPTION_*'),
    'a future secret-shaped TRANSCRIPTION_ variable would be baked automatically');
  const expected = [
    'TRANSCRIPTION_ENGINE',
    'TRANSCRIPTION_CHUNK_SECONDS',
    'TRANSCRIPTION_CHUNK_OVERLAP_SECONDS',
    'TRANSCRIPTION_BOUNDARY_SLACK_SECONDS',
    'TRANSCRIPTION_LOCAL_MODEL',
    'TRANSCRIPTION_VAD',
    'TRANSCRIPTION_LANGUAGE',
  ];
  const actual = [...new Set(
    settingsArm.match(/\bTRANSCRIPTION_[A-Z0-9_]+\b/g) ?? [],
  )].sort();
  assert.deepEqual(actual, [...expected].sort(),
    `distribution transcription allowlist changed: ${actual.join(', ')}`);
});

test('runtime cloud paths use injected Keychain BYOK and have no backend fallback', () => {
  const config = read('app', 'Sources', 'MeetGPT', 'Config.swift');
  const state = read('app', 'Sources', 'MeetGPT', 'AppState.swift');
  const envExample = read('app', '.env.example');

  assert.match(config,
    /static var deepgramAPIKey:[^{]+\{\s*ProviderKeyStore\.current\.transcriptionKey\(for: \.deepgram\)/s);
  assert.match(config,
    /static var assemblyAIAPIKey:[^{]+\{\s*ProviderKeyStore\.current\.transcriptionKey\(for: \.assemblyAI\)/s);

  assert.match(state,
    /providerKeys\.transcriptionKey\(for: \.deepgram\)/,
    'Deepgram does not read its key from the AppState-injected store');
  assert.match(state,
    /providerKeys\.transcriptionKey\(for: \.assemblyAI\)/,
    'AssemblyAI does not read its key from the AppState-injected store');
  assert.ok(!state.includes('DeepgramBackend.'),
    'AppState can still mint/report a first-party Deepgram grant');
  assert.ok(!state.includes('ServerDiarizationService.'),
    'AppState can still upload diarization audio through a first-party server');
  assert.match(config,
    /guard TranscriptionEngine\.selectableCases\.contains\(engine\) else \{ return false \}/,
    'a hidden saved transcription engine can become an audio-upload route');
  assert.match(state,
    /transcriptionEngineAvailability:[\s\S]{0,900}case \.whisper: return false[\s\S]{0,120}case \.local, \.server: return Config\.engineAvailable/,
    'the production AppState policy can enable the hidden Whisper upload route');
  assert.ok(!envExample.includes('| whisper (OpenAI Whisper cloud)'),
    '.env.example still advertises the hidden chat-key audio route');
});
